language: cpp

compiler:
  - gcc
  - clang

cache:
  - apt
  - ccache

sudo: false

addons:
  apt:
    packages:
      - autopoint
      - libdb-dev
      - libreadline-dev
      - libssl-dev
      - libwww-perl
      - xsltproc
      - zlib1g-dev

before_script:
  - ccache -s
  - ./autogen.sh
  - ./configure CC="ccache $CC" CXX="ccache $CXX"
  - grep CXX config.status
  - make

script:
  - make test
  - ccache -s
