book1.html  x26.html  x31.html  x45.html  x50.html  x57.html  x61.html \
intro.html  x28.html  x43.html  x46.html  x52.html  x60.html  x64.html: \
boxi.docbook
	jade -d /usr/share/sgml/stylesheet/dsssl/sgmltools/html.dsl \
		-t xml /usr/share/xml/declaration/xml.dcl boxi.docbook

