=head1 Boxi

A graphical user interface for Box Backup, the online encrypted backup
system by Ben Summers.



=head2 Summary

Boxi is a graphical user interface to configure, manage, and administer
the Internet backup software called Box Backup by Ben Summers, available from
L<http://www.fluffy.co.uk/boxbackup>.

Box Backup is "an open source, completely automatic on-line backup system
for UNIX" with the following advantages:

=over

=item *
File Based

All backed up data is stored on the server in files on a filesystem
-- no tape or archive devices are used 

=item *
Untrusted Servers

The server is trusted only to make files available when they are
required -- all data is encrypted on the client

=item *
Automatic Backups

A backup daemon runs on systems to be backed up, and copies
encrypted data to the server when it notices changes 

=item *
Bandwidth Efficient

Only changes within files are sent to the server, just like rsync 

=item *
Storage Efficient

Old versions of files on the server are stored as changes from
the current version 

=item *
File Versioning

Behaves like tape -- old versions and deleted files are available 

=item *
Low Cost and Portable

Designed to be easy and cheap to run a server. Portable implementation,
and optional RAID implemented in userland for reliability without complex
server setup or expensive hardware

=back

Boxi is a graphical user interface to allow easy configuration and
administration of the Box Backup client, and access to files on the server.

Boxi is developed in C++ using the wxWidgets GUI toolkit, available from
L<http://www.wxwidgets.org/>. This means that it should be possible in
theory to compile Boxi on Windows, Macintosh and most UNIX systems,
although so far only the following systems have been tested:

=over 4

=item *
Fedora Core 2 (Linux)

=item *
SuSE Professional 9.1 (Linux)

=item *
Ubuntu 5.04 (Linux, thanks to Scott Langley)

=item *
Cygwin on Windows XP

=back

Feedback about and patches for compatibility with other systems are 
most welcome.



=head2 Download

The latest stable version of Boxi is 0.1.0.

=over

=item Source code for all platforms (version 0.1.0)

L<http://prdownloads.sourceforge.net/boxi/boxi-0.1.0.tar.gz?download>

=item Compiled executable for Windows/Cygwin (version 0.0.7)

L<http://prdownloads.sourceforge.net/boxi/boxi-0_0_7.zip?download>

=item Latest source code from CVS

The latest source code is experimental, a work in progress, and not guaranteed
to compile or run on any system. Your mileage may vary. You can get it from
Sourceforge's CVS server:

 cvs -d:pserver:anonymous@cvs.sourceforge.net:/cvsroot/boxi login 
 
 cvs -z3 -d:pserver:anonymous@cvs.sourceforge.net:/cvsroot/boxi co -P boxi

L<http://sourceforge.net/cvs/?group_id=135105>

=back

=head2 Compiling

Boxi is distributed as source code, and binaries for Windows/Cygwin. 
Source code must be compiled before use.

The following programs and libraries are required to compile Boxi:

=over

=item *
perl (version 5.8 or higher)

=item *
patchutils (or at least patch)

=item *
openssl (version 0.9.7a or higher, with development libraries)

=item *
libncurses-devel (version 5, for boxbackup)

=item *
gcc, g++ and libstdc++-devel

=item *
wxWindows (version 2.6.0 or 2.4.2, with development libraries)

=back

If you are working from a CVS checkout, you will also need:

=over 4

=item *
m4 (version 1.4.1 or higher)

=item *
autoconf (version 2.59 or higher)

=item *
automake (version 1.8.3 or higher)

=item *
libtool (version 1.5.6 or higher)

=back

CVS users need to run these commands first:

	./autogen.sh
	./make-image-headers.pl

If you downloaded a release version, just extract the contents of the
archive, and change into the directory it creates (e.g. boxi-0.1.0).

For all users, it should be enough to then run the following commands:

	./configure
	make

Don't even think about installing it yet! There really isn't any point.
Run "src/boxi [-c] [<config-file>]" to start the GUI. 

The "-c" option is ignored if present, and provided to comfort those
more familiar with the Box Backup command-line tools.



=head2 Screenshots

No project would be complete without a gratuitous display of the author's
skill at creating awful user interfaces:

=for illustration daemonctrl.png

=for illustration config.png

=for illustration locations.png

=for illustration filelist.png



=head2 Changes

This software is currently experimental. I hope that you will try it and
find it useful, but it doesn't come with any warranty, not even that
it won't give your dog hiccups. If it breaks, you get to keep both pieces.

=head3 A note about versions

Henceforth, odd minor numbers (x.1.y, x.3.y, etc.) will be experimental,
and even numbers (x.2.y, x.4.y) slightly less experimental (maybe stable
one day).

=over

=item Version 0.1.0 (released 2005-05-26)

L<http://prdownloads.sourceforge.net/boxi/boxi-0.1.0.tar.gz?download>

Commemorates the release of public CVS, and interest of other developers
in joining in the project, with a minor version number increase. 

Fixed compilation on wxWindows 2.6.0 (at least on Cygwin, hopefully Linux
too).

Tweaked Box Backup's build infrastructure to require fewer rebuilds,
while still satisfying dependencies (I hope :-)

=item Version 0.0.7 (released 2005-05-21)

L<http://www.qwirx.com/boxi/boxi-0.0.7.tar.gz>

No need to start with the name of a configuration file any more!
Built-in defaults for configuration values.

Load configurations from a file while Boxi is running.

Prompt to save configuration changes when exiting Boxi.

Checks configuration for errors in real time while editing.

Fewer pop-up warnings on Cygwin.

First binary release for Windows (Cygwin).

=item Version 0.0.6 (released 2005-05-08)

L<http://www.qwirx.com/boxi/boxi-0.0.6.tar.gz> (released 2005-05-08)

Server Files panel: hide deleted files and old versions of files on the 
server (see the new "View" menu). Disable Delete/Undelete buttons when
a file is selected (need a protocol change to make this work for files).

Locations panel: edit and remove backup locations.

Local Files panel: view include/exclude status and reasons for local files.

Backup Daemon panel: new GUI control panel for the bbackupd daemon. Start and
stop the daemon, kill it, ask it to sync or reload (with Real Buttons(TM)).

Box Backup: integrated build process with GNU autotools. Fixed "make clean"
to do what I want (ensure a rebuild next time). Fixed "make" to work properly
when remaking after a code change. Moved command socket handling to a
separate class, to make it easier to access from other places in the code.
Listen for command socket connections and commands while a backup is in
progress, while sleeping on error, and while sleeping on store full.

Server Connection: new class to encapsulate server interface.

General: fixed Cygwin (more or less, perhaps less :-). Many thanks to
Gary for his enthusiasm pushing me to make this happen.

The code is stable, but not all new (or existing!) features work perfectly.
The interface to control Local Files checking on server needs more work.
Some things, like location matching, don't work on Cygwin but do work on
Linux (and possibly other Unixes).

=item Version 0.0.5

L<http://www.qwirx.com/boxi/boxi-0.0.5.tar.gz> (released 2005-03-19)

Separated configuration settings into Basic and Advanced, to be less
intimidating for new users and to fit more easily into the available
screen space.

Allow navigating into directories by double-clicking files in the server
file list (similar to Windows Explorer behaviour).

Allow sorting the file list by filename, size or date, in forward or 
reverse order. Replaced the "Flags" column by "Last Modified" date, which
is more useful.

Redraw the GUI during directory restore operations, showing progress in the
status bar (current file and number of files restored).

Changed most error message dialogs to have more politically-correct titles
(Boxi Error and Boxi Message).

Added the "-c" command-line option, which is ignored, and renamed README.txt 
back to README, to stop Make from complaining.

Many thanks to Richard Eigenmann for these suggestions.

=item Version 0.0.4 

L<http://www.qwirx.com/boxi/boxi-0.0.4.tar.gz> (released 2005-03-14)

Added the ability to restore files and directories from the server,
and to delete and undelete directories.

Fixed many crashes due to server disconnecting during operation,
and internal buffer overflows in Box Backup's debugging code.

Display file sizes (nicely formatted) in the server file list.

=item Version 0.0.3

L<http://www.qwirx.com/boxi/boxi-0.0.3.tar.gz> (released 2005-03-01)

Split the code into multiple files (modules), which should make it
easier to understand and faster to recompile after making changes.

Fixed a bug that made it impossible to connect to the server
and browse files stored there, since before version 0.0.2 was released.

Missing essential configuration parameters are detected when trying
to connect to the server, and a warning is given.

Exceptions are handled much better, with Real Error Messages(TM).

You can now save your changes to the configuration file by selecting
the "Save" option from the "File" menu. This feature should be used
with extreme caution! PLEASE back up your configuration file first!

=back



=head2 Bugs

I<"There are no bugs, just undocumented features" (unknown)>

See the TODO file for a list of bugs to fix and features which are planned 
for future releases. Feel free to contribute patches or suggestions for new
features :-)



=head2 License

This software is copyright (C) Chris Wilson <boxi_README@qwirx.com>, 2004-05.
Licensed for public distribution under the GNU General Public License (GPL),
version 2 or later (L<http://www.gnu.org/licenses/gpl.html>).

Contains a copy of Box Backup by Ben Summers, which is separately licensed
under a license very similar to the BSD license, which can be seen at
L<http://www.fluffy.co.uk/boxbackup/license.html>. This component is NOT
covered by the GPL.

The file boxbackup.patch contains a number of changes to Box Backup which
are useful for Boxi. That file is under the same license as Box Backup,
i.e. a BSD-like license, and copyright assigned to Ben Summers.

Portions of Boxi are copied, based on or inspired by Box Backup
itself, and it is not possible to compile Boxi without linking to 
the Box Backup code. Therefore, the Boxi code contains the attribution
required by the Box Backup license, that it contains code by Ben Summers.
This attribution B<must not> be removed from the code!

Generously hosted by SourceForge:

=for html <p><A href="http://sourceforge.net"> <IMG src="http://sourceforge.net/sflogo.php?group_id=135105&amp;type=5" width="210" height="62" border="0" alt="SourceForge.net Logo" /></A></p>

=for html <p><a href="http://sourceforge.net/donate/index.php?group_id=135105"><img src="http://images.sourceforge.net/images/project-support.jpg" width="88" height="32" border="0" alt="Support This Project" /></a></p>
